[package]
name = "gtktest"
version = "0.1.0"
authors = ["Gareth Hubball <ridecar2@gmail.com>"]

[dependencies]
actix-web = "0.7"
ears = "0.5.1"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_10"]